/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#151316",
        "surface-container-highest": "#373437",
        "surface-bright": "#3b383c",
        "tertiary-fixed-dim": "#ffb3b6",
        "on-tertiary-container": "#582328",
        "on-secondary-fixed-variant": "#862025",
        "inverse-on-surface": "#322f33",
        background: "#151316",
        "inverse-primary": "#954836",
        "primary-fixed": "#ffdad2",
        "outline-variant": "#54433f",
        "secondary-fixed": "#ffdad8",
        "on-tertiary-fixed-variant": "#6f353a",
        primary: "#ffb4a4",
        "on-tertiary-fixed": "#390b11",
        "surface-container": "#211f22",
        outline: "#a28c87",
        "on-secondary-fixed": "#410006",
        "surface-tint": "#ffb4a4",
        "surface-container-low": "#1d1b1e",
        tertiary: "#ffb3b6",
        "on-primary": "#5a1b0d",
        "tertiary-fixed": "#ffdada",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#ffb3b0",
        secondary: "#ffb3b0",
        surface: "#151316",
        "on-primary-container": "#5e1e10",
        "surface-container-lowest": "#0f0d10",
        "on-secondary": "#660611",
        "surface-container-high": "#2c292c",
        "inverse-surface": "#e7e1e5",
        "on-background": "#e7e1e5",
        "primary-container": "#e0836e",
        "secondary-container": "#862025",
        error: "#ffb4ab",
        "on-primary-fixed-variant": "#773121",
        "tertiary-container": "#d2888c",
        "primary-fixed-dim": "#ffb4a4",
        "on-primary-fixed": "#3d0600",
        "on-tertiary": "#531f24",
        "on-error": "#690005",
        "on-surface-variant": "#dac1bc",
        "on-secondary-container": "#ff9995",
        "on-surface": "#e7e1e5",
        "surface-variant": "#373437",
        brand: {
          charcoal: "#0d0b0e",
          deepCrimson: "#2a0a0d",
          crimsonGlow: "#7a1921",
          terracotta: "#e07a5f",
          terracottaLight: "#f4a261",
          gold: "#e9c46a",
          cardBg: "rgba(23, 18, 22, 0.72)",
          surfaceGlow: "rgba(224, 122, 95, 0.12)",
        },
      },
      animation: {
        "spin-slow": "nocturneSpin 22s linear infinite",
        "pulse-subtle": "pulseGlow 4s ease-in-out infinite",
      },
      keyframes: {
        pulseGlow: {
          "0%, 100%": { opacity: "0.45", transform: "scale(1)" },
          "50%": { opacity: "0.7", transform: "scale(1.06)" },
        },
        nocturneSpin: {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        "space-sm": "0.5rem", gutter: "1.25rem", "space-lg": "1.5rem",
        "space-md": "1rem", margin: "1.75rem", "space-xl": "2.25rem", "space-xs": "0.25rem",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        serif: ["Playfair Display", "Georgia", "serif"],
        "label-md": ["Plus Jakarta Sans"], "display-hero": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"], "headline-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"], "label-sm": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"], "body-md": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"], "label-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "display-hero": ["44px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-lg": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-sm": ["17px", { lineHeight: "22px", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.06em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "18px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
